site_name: RayNet
repo_url: https://github.com/paschalidoud/raynet
theme: readthedocs
site_dir: output
extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
    - mdx_math
pages:
- Home: 'index.md'
- Documentation:
  - Installation: 'installation.md'
  - Getting started: 'getting-started.md'
  - Console applications: 'console-applications.md'
  - Contribution: 'contribution.md'
- Code Walkthrough: 'code-walkthrough.md'
- Examples:
  - Designing and training your own Multi-View CNN: 'custom-mvcnn.md'
  - Qualitative Results from DTU Dataset: 'dtu-results.md'
  - Qualitative Results from Aerial Dataset: 'restrepo-results.md'
